### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by nikku**
Attempt to address CI failures due to dependency bumps.

Things work fine on my machine (Ubuntu Linux):

image

### CODE REVIEW

**Comment by barmac** [comment]
My first try failed with:

```
> bpmn-js-integration@0.0.1 mocha
> mocha --reporter spec -r test/expect.js test/spec/base/base.js test/spec/modeling/modeling.js test/spec/miwg/miwg.js



  1) "before all" hook: openBrowser in "{root}"

  0 passing (2s)
  1 failing

  1) "before all" hook: openBrowser in "{root}":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7)
```

but another was OK.

Note that I had to `^C` the process, and I believe this is the reason of 6h timeout on CI. So this PR does not fix this, but it allowed to reproduce the problem locally.

**Comment by barmac** [comment]
My first try failed with:

```
> bpmn-js-integration@0.0.1 mocha
> mocha --reporter spec -r test/expect.js test/spec/base/base.js test/spec/modeling/modeling.js test/spec/miwg/miwg.js



  1) "before all" hook: openBrowser in "{root}"

  0 passing (2s)
  1 failing

  1) "before all" hook: openBrowser in "{root}":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7)
```

but another was OK.

Note that I had to `^C` the process, and I believe this is the reason of 6h timeout on CI. So this PR does not fix this, but it allowed to reproduce the problem locally.

**Comment by barmac** [comment]
With the change below, we can reliably reproduce the tests hanging after timeout:

```diff
before(async function openBrowser() {
   browser = await puppeteer.launch({
     headless: 'new'
   });
+
+  await new Promise(resolve => setTimeout(() => {
+    console.log('test timeout');
+    resolve();
+  }, 5000));
 });
```

I will check mocha options to make it fail immediately after timeout fires.

**Comment by barmac** [comment]
The hanging timeout issue is fixed via https://github.com/bpmn-io/bpmn-js-integration/pull/58/commits/fa63976c32d4521e2da55fabb10aeac2eb29a673

I also increased the timeout for browser opening since it fails usually due to missing resources on the runner and not because of a problem with the project.

**Comment by nikku** [comment]
:clap:

**Pull request merged**
