### PR TITLE
fix: build before running the tests

### PR DESCRIPTION
**Pull request by barmac**
Now it should work.

### CODE REVIEW

**Review by nikku — APPROVED** [review]

**Comment by barmac** [comment]
It still doesn't, though I am super close: https://github.com/bpmn-io/bpmn-js-integration/actions/runs/3248989623/jobs/5330863432

**Comment by barmac** [comment]
OK so the flow almost worked: https://github.com/bpmn-io/bpmn-js-integration/actions/runs/3249016129/jobs/5330921759#step:7:279

The only thing to fix is permissions.

**Comment by nikku** [comment]
Last bug not fixed yet, but I#m still approving this :grin:

**Comment by barmac** [comment]
Yeah, the bot doesn't have write access to the test suite fork -> the push fails.

**Comment by barmac** [comment]
This should now succeed: https://github.com/bpmn-io/bpmn-js-integration/actions/runs/3249016129

**Comment by barmac** [comment]
It worked: https://github.com/bpmn-miwg/bpmn-miwg-test-suite/compare/master...bpmn-io:bpmn-miwg-test-suite:submit-10.2.0

**Comment by barmac** [comment]
I will remove the branch after the presentation, as we are not submitting new results right now.

**Pull request merged**
